[package]
name = "learn_rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name="guessing_main"
path="src/bin/guessing_game.rs"

[[bin]]
name="stack_application"
path="src/bin/stack_application.rs"

[dependencies]
rand = "0.9.2"
